baseURL = 'http://blog.shgmn.com'
languageCode = 'ja-jp'
title = 'しげもんblog'
theme = 'github-style'
googleAnalytics = "G-8XKVKVZQ3G"

[params]
  author = "Takuya Shigemoto"
  github = "shgmn"
  facebook = "shigemoto.takuya"
  twitter = "shgmn9"
  instagram = "shgmn"
  url = "https://shgmn.com/"
  rss = true
  lastmod = true
  avatar = "/images/shgmn.png"
  favicon = "/images/shgmn.png"

